#!/usr/bin/env bash
# Install the local git pre-commit hooks (Task 9 security hardening).
#
# Wires ops/check_secrets.sh as a pre-commit hook so credential-shaped strings
# can never be committed by accident. Run once per clone:
#
#   ops/install_git_hooks.sh
#
# Git hooks are NOT tracked by git, so every clone must run this. The hook simply
# delegates to the tracked ops/check_secrets.sh, which is the source of truth.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK="$HOOK_DIR/pre-commit"

mkdir -p "$HOOK_DIR"
cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by ops/install_git_hooks.sh — delegates to the tracked scanner.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"
exec "$REPO_ROOT/ops/check_secrets.sh"
EOF
chmod +x "$HOOK"
chmod +x "$REPO_ROOT/ops/check_secrets.sh"

echo "Installed pre-commit secrets hook -> $HOOK"
echo "It runs ops/check_secrets.sh on every commit. Bypass (discouraged): git commit --no-verify"
